name: Production Deployment
on:
  push:
    tags: ['v*']
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      registry: registry.gitlab.com
      context: production
      environment: production
      setenv: env.DOMAIN=${{contains(github.ref_name, 'alpha' && 'alpha.')}}iconicompany.ru
