name: Prerelease Deployment
on:
  push:
    tags: ['v*-*']
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      registry: registry.gitlab.com/${{ github.repository }}
      context: production
      env: production-alpha
      setenv: env.DOMAIN=alpha.iconicompany.ru
