name: Production Deployment
on:
  push:
    tags: ['*']

jobs:

  call-converge:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      registry: registry.gitlab.com
      context: production
      environment: production
      setenv: env.DOMAIN=iconicompany.ru
