name: Production Deployment
on:
  push:
    tags: ['v*','!v*-*']
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      registry: registry.gitlab.com/${{ github.repository }}
      context: production
      environment: production
      setenv: env.DOMAIN=iconicompany.ru
