name: Generate KUBECONFIG
on:
    workflow_call:
      inputs:
        CLUSTER_URL:
          description: Cluser URL, e.g. https://kube01.icncd.ru:6443
          type: string
          default: https://kube01.icncd.ru:6443
        CERTIFICATEAUTHORITY:
          description: "Certificate authority"
          type: string
        CERTIFICATE:
          description: "X509 certificate"
          type: string
        PRIVATEKEY:
          description: "Private key"
          type: string
      # Map the workflow outputs to job outputs
      outputs:
        KUBE_CONFIG:
          description: "KUBECONFIG in BASE64"
          value: ${{ jobs.genkubeconfig.outputs.KUBE_CONFIG }}
jobs:
  genkubeconfig:
    runs-on: ubuntu-latest
    outputs:
        KUBE_CONFIG: ${{ steps.genkubeconfig.outputs.KUBE_CONFIG }}
    steps:
      - name: Render KUBECONFIG YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./kubeconfig.template.yaml
          output: ./kubeconfig.yaml
        env:
          CA_DATA: 1.2.3
          CERTIFICATE_DATA: staging
          PRIVATEKEY_DATA: test
      - name: Create KUBECONF
        id: genkubeconfig
        run: |
          echo 'KUBE_CONFIG<<EOF' >> $GITHUB_OUTPUT
          cat kubeconfig.yaml | base64 >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT


