name: Playwright
on:
  workflow_call:
    inputs:
      env:
        description: Werf env (production, branch name, pull request number, etc). Default value is branch/tag name "github.head_ref || github.ref_name"
        type: string
      setenv:
        description: WERFTEST_URL.
        type: string


env:
  WERFTEST_URL: ${{ inputs.setenv }}

jobs:
  test:
    name: Playwright
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Take params branch
        run: echo "branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
        id: branch_name
      - name: Run Playwright tests
        timeout-minutes: 15
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
